const {test}=require('node:test'),assert=require('node:assert/strict');
const C=require('../dist/core.js'),I=require('../dist/excel-import.js'),R=require('../dist/renaper-model.js'),X=require('../dist/vendor/xlsx.full.min.js');
function workbook(overrides={}){const rows=[['24 de septiembre','','Mix','Capacidad:',2],[],['N°','','Nombres','Apellido','DNI','Fecha de Nacimiento','Punto de carga','Observación','Sexo'],[1,true,'Ana','Prueba','12345678','01/02/2000','Terminal','Detalle','F'],[2,false,'Luis','Prueba','23456789','2001-03-04','Centro','','M']];const sheet=X.utils.aoa_to_sheet(rows);for(const [key,v]of Object.entries(overrides))sheet[key]={v,t:typeof v==='number'?'n':'s'};const wb=X.utils.book_new();X.utils.book_append_sheet(wb,sheet,'Primera');X.utils.book_append_sheet(wb,X.utils.aoa_to_sheet([['Ignorar totalmente']]),'Otra');return X.write(wb,{type:'buffer',bookType:'xlsx'});}
test('Importa solamente la primera hoja, sexo I, sin plano ni embarques heredados',()=>{const p=I.read(workbook(),X);assert.equal(p.passengers.length,2);assert.equal(p.departure,'');assert.deepEqual(p.errors,[]);const t=I.build(p,'2026-09-24');assert.equal(t.capacity,2);assert.equal(t.vehicle,'Mix');assert.equal(t.layoutMode,'list');assert.deepEqual(t.floors,[]);assert.equal(t.passengers[0].sex,'F');assert.equal(t.passengers[0].birthDate,'2000-02-01');assert.equal(t.passengers[0].sourceCheck,true);assert.equal(t.passengers[0].boarded,false);assert.equal(t.passengers[0].seatId,'');assert.throws(()=>I.build(p,''),/fecha/);});
test('Detecta exceso de capacidad, documentos repetidos y sexo inválido sin guardar parcialmente',()=>{assert.match(I.read(workbook({E1:1}),X).errors.join(),/capacidad|lugares/);assert.match(I.read(workbook({E5:'12345678'}),X).errors.join(),/repetido/);assert.match(I.read(workbook({I4:'Z'}),X).errors.join(),/Sexo/);});
test('Nacimiento y fecha imposibles no pasan validación',()=>{assert.throws(()=>I.build(I.read(workbook({F4:'31/02/2000'}),X),'2026-09-24'),/nacimiento/);assert.throws(()=>I.build(I.read(workbook(),X),'2026-02-31'),/Fecha/);});
test('Lista importada controla capacidad al editar y añadir; permite infante sin lugar',()=>{const t=I.build(I.read(workbook(),X),'2026-09-24');assert.doesNotThrow(()=>C.savePassenger(t,{...t.passengers[0],phone:'123'}));const p={...C.blankPassenger(),firstName:'Extra',lastName:'Prueba'};assert.throws(()=>C.savePassenger(t,p),/capacidad/);assert.doesNotThrow(()=>C.savePassenger(t,{...p,noSeat:true}));assert.doesNotThrow(()=>C.validateStore({version:1,trips:[t]}));});
test('Respaldos anteriores reciben campos nuevos de DNI vacíos',()=>{const t=C.blankTrip(),p={...C.blankPassenger(),firstName:'Ana',lastName:'Prueba'};for(const k of ['dniCopy','dniCheckedAt','dniQueryKey','dniSource','renaperStatus'])delete p[k];t.passengers.push(p);C.validateTrip(t);assert.equal(p.dniCopy,'');});
test('A1 día/mes y B1 año forman fecha; rechaza años contradictorios',()=>{assert.equal(I.read(workbook({B1:2027}),X).departure,'2027-09-24');assert.equal(I.read(workbook({A1:'24/09',B1:2028}),X).departure,'2028-09-24');assert.match(I.read(workbook({B1:'27'}),X).errors.join(),/B1/);assert.match(I.read(workbook({A1:'2026-09-24',B1:2027}),X).errors.join(),/coincide/);});
test('RENAPER requiere los tres datos y descarta mensajes de error o ambiguos',()=>{assert.throws(()=>R.request({documentType:'DNI',document:'12345678',sex:'',birthDate:'2000-01-01'}));assert.equal(R.request({documentType:'DNI',document:'12.345.678',sex:'X',birthDate:'2000-01-01'}).dni,'12345678');assert.equal(R.parse('El ejemplar vigente para el documento ingresado es: B'),'B');assert.equal(R.parse('El ejemplar vigente es el ejemplar AA.'),'AA');for(const text of ['El ejemplar vigente es: No encontrado','El ejemplar vigente es: NO','Error al consultar','El ejemplar vigente es: B. Pero está anulado'])assert.equal(R.parse(text),'');});

test('Reconoce respuesta real de RENAPER con fecha de emisión y saltos de línea',()=>{assert.equal(R.parse('El ejemplar vigente para el documento ingresado es: B, con fecha de emisión el 15/02/2025'),'B');assert.equal(R.parse('El ejemplar vigente para el documento ingresado es: AA, con\nfecha de emisión el 15/02/2025'),'AA');assert.equal(R.parse('El ejemplar vigente para el documento ingresado es: B, con fecha de emisión el 15/02/2025. Pero está anulado'),'');});
