const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),C=require('../dist/core.js');
test('Arranca la aplicación con una salida importada y dibuja resumen, pasajeros y choferes',()=>{
 const t=C.blankTrip();Object.assign(t,{layoutMode:'list',capacity:58,floors:[],configured:true});t.passengers.push({...C.blankPassenger(),firstName:'Persona',lastName:'Prueba'});
 const nodes=new Map();const element=()=>({innerHTML:'',textContent:'',classList:{add(){},remove(){}},addEventListener(){},before(){},after(){},append(){}});
 const doc={querySelector:s=>{if(!nodes.has(s))nodes.set(s,element());return nodes.get(s);},createElement:element,addEventListener(){}};
 const ctx={Coral:C,CoralCloud:{mode:'local',snapshot:()=>({data:{version:1,trips:[t]}})},document:doc,window:{addEventListener(){}},localStorage:{getItem:()=>null},structuredClone,console};vm.createContext(ctx);
 vm.runInContext(fs.readFileSync(require.resolve('../dist/app.js'),'utf8'),ctx);
 assert.match(nodes.get('#main').innerHTML,/Preparación de la salida/);
 vm.runInContext("view='passengers';render()",ctx);assert.match(nodes.get('#main').innerHTML,/Persona Prueba/);
 vm.runInContext("view='rooming';render()",ctx);assert.match(nodes.get('#main').innerHTML,/Pousada Mon Chateau/);assert.match(nodes.get('#main').innerHTML,/Apart Abaeté/);vm.runInContext("view='drivers';render()",ctx);assert.match(nodes.get('#main').innerHTML,/Agregar chofer/);
 const second=C.blankTrip();Object.assign(second,{name:'Otra salida',layoutMode:'list',capacity:42,floors:[],configured:true});ctx.second=second;
 vm.runInContext("data.trips.push(second);view='rooming';render()",ctx);
 nodes.get('#trip-select').onchange({target:{value:second.id}});
 assert.equal(vm.runInContext('view',ctx),'rooming');assert.equal(vm.runInContext('activeId',ctx),second.id);
 assert.match(nodes.get('#main').innerHTML,/Creá habitaciones/);
 vm.runInContext("view='documents';render()",ctx);assert.doesNotMatch(nodes.get('#main').innerHTML,/<h2>Lista de pasajeros<\/h2>/);
 const original=vm.runInContext('JSON.stringify(data.trips[0].passengers)',ctx);
 vm.runInContext("data.trips[0].archived=true;activeId=data.trips[0].id;view='overview';render()",ctx);
 assert.equal(vm.runInContext('activeId',ctx),second.id);
 assert.equal(vm.runInContext('JSON.stringify(data.trips[0].passengers)',ctx),original);
 vm.runInContext("data.trips[1].archived=true;view='archived';render()",ctx);
 assert.equal(vm.runInContext('activeId',ctx),'');assert.match(nodes.get('#main').innerHTML,/Restaurar salida/);assert.doesNotMatch(nodes.get('#trip-select').innerHTML,/Otra salida/);
 vm.runInContext("data.trips[0].archived=false;view='overview';render()",ctx);assert.equal(vm.runInContext('activeId',ctx),t.id);
});
