'use strict';
const http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'../dist');
const lan=process.argv.includes('--lan'),port=Number(process.argv.find(x=>x.startsWith('--port='))?.split('=')[1]||(lan?4174:4173));
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png'};
const server=http.createServer((req,res)=>{try{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);const file=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(file!==root&&!file.startsWith(root+path.sep)){res.writeHead(403);res.end();return;}fs.readFile(file,(err,content)=>{if(err){res.writeHead(404);res.end('No encontrado');return;}const ext=path.extname(file);if(ext==='.html')content=content.toString().replace('src="cloud.js"','src="local-store.js"').replace('En la nube','En este equipo').replace(/Sincronizado con Firebase|Guardado en Firebase/g,'Guardado local').replace('Guardado en Firebase · Acceso privado · Conservá también tus respaldos.','Versión local de prueba · Descargá respaldos para conservar tus datos.').replace('Sincronización con Firebase. Cada ingreso se pone en verde después de guardarse. Necesitás conexión a Internet para registrar cambios.','Guardado en este navegador. Los cambios de esta versión local no se envían a Firebase.');if(ext==='.js'&&['app.js','embarque.js'].includes(path.basename(file)))content=content.toString().replace(/Guardado en Firebase|guardados en Firebase|guardado en Firebase|Sincronizado con Firebase/g,'Guardado local').replace('Tus salidas se guardan en Firebase y se sincronizan con el iPad. También podés descargar un respaldo independiente.','Esta versión guarda las salidas en este navegador. Descargá un respaldo para trasladarlas a otro equipo.');res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(content);});}catch(e){res.writeHead(400);res.end('Solicitud inválida');}});
server.listen(port,lan?'0.0.0.0':'127.0.0.1',()=>{
  console.log(`Coral local: http://127.0.0.1:${port}`);
  if(lan){for(const addresses of Object.values(require('node:os').networkInterfaces()))for(const address of addresses||[])if(address.family==='IPv4'&&!address.internal)console.log(`iPad, misma Wi-Fi: http://${address.address}:${port}/embarque.html`);console.log('Solo se sirve la aplicación. Cargar respaldo en el iPad; los datos no se sincronizan.');}
});
server.on('error',e=>{console.error(e.code==='EADDRINUSE'?`El puerto ${port} ya está en uso. Cerrá la otra instancia o abrí http://127.0.0.1:${port}`:e.message);process.exitCode=1;});
